### ISSUE TITLE
Lots of warning with gcc 4.9.2 + shared_ptr detection fails with cmake

### ISSUE THREAD

**Issue by theodelrieu** [kisli/vmime#126]
Hi, I compiled vmime with gcc 4.9.2 with c++11 support today, and I had an issue on shared_ptr detection.
It appears the tests you run to check c++11 are built without the '-std=c++11' flag.
It's fixed with 'CXXFLAGS=-std=c++11 cmake -G etcetc'

Secondly, I had a lot of warnings, mainly due to std::auto_ptr, which is deprecated in c++11, and will be removed in c++17, and should be replaced with unique_ptr when c++11 is detected. Then there is sign comparison mismatch and long to int conversions.

I can help fixing those warnings, but I'd like to have your opinion on how to proceed, since I didn't have a lot of time to look at the code in details for now. I don't want to go against the design of the lib, and make us both lose time. (I read the style guidelines though)

**Comment by JonnyPtn** [comment]
For reference, I get a butt load of warnings when compiling on Windows too (4996 to be precise!). The majority are "X needs to have dll-interface", which I don't really want to mess with, but there are a handful of signed/unsigned mismatches and unreferenced local vars which should be straightforward to tackle.

Happy to iron out a few of the simple warnings unless there's a specific reason not to?

**Comment by vincent-richard** [comment]
Hi!

As for the shared_ptr detection issue, not forcing "-std=c++11" is intended because it is not a standard argument, and VMime can be compiled with other compilers than gcc (for example, clang). C++14 will be the default for gcc 6 IIRC.

I have replaced the use of deprecated 'auto_ptr' at several places in the code (commit 68ad348).

Unfortunately, I don't have access to a Windows platform at the moment, so I can't fix Windows-related warnings. I will look at the other warnings, but that's lot of work. And no, there is no specific reason not to fix them, only lack of time. :-)

**Comment by vincent-richard** [comment]
Fixed a lot of warnings with the latest commits, so I am closing the issue.
Please feel free to reopen if needed.
